version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-web
    versions:
    - 0.14.10
    - 0.14.11
    - 0.14.12
    - 0.15.0
    - 0.15.1
    - 0.15.3
    - 0.15.5
    - 0.15.6
    - 0.15.7
    - 0.16.0
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: react-native-reanimated
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.1.9
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.9.0
